A-Marzouk/civ

public/mix-manifest.json

New video promo added on lading page

Eduardo Acosta

---

resources/js/components/resume_themes/theme403.vue

fixed theme403 header left block

fixed theme403 header block

---

resources/js/components/resume_themes/theme900/index.vue

fix theme900

---

package-lock.json
resources/js/components/resume_builder/components/utils/currency-input.vue
resources/js/components/resume_builder/components/utils/index.vue
resources/js/components/resume_builder/tabs/edit_tabs/Education.vue
resources/js/components/resume_builder/tabs/edit_tabs/education_tabs/school.vue
resources/sass/resume_builder/components/inputs.scss

Input for pay availability tab

Created currency input

---

database/migrations/2020_05_26_070228_create_url_permissions_table.php

Fix: change of the order of deleting tables.

---

resources/js/components/resume_builder/tabs/edit_tabs/Portfolio.vue
resources/js/components/resume_builder/tabs/edit_tabs/education_tabs/school.vue

Fixed responsive issues on these tabs

Responsive portfolio and education tab

---

resources/js/components/resume_builder/tabs/edit_tabs/Skills.vue
resources/js/components/resume_themes/theme511/index.vue

- Update theme 511 as default.

Master to Production Regualr

---

app/Http/Controllers/API/AchievementsController.php
app/Http/Controllers/API/ProjectsController.php
resources/js/components/resume_builder/tabs/edit_tabs/Achievement.vue
resources/js/components/resume_builder/tabs/edit_tabs/Hobbies.vue
resources/js/components/resume_builder/tabs/edit_tabs/Links.vue
resources/js/components/resume_builder/tabs/edit_tabs/Portfolio.vue
resources/js/components/resume_builder/tabs/edit_tabs/Skills.vue
resources/js/components/resume_builder/tabs/edit_tabs/WorkExperience.vue
resources/js/components/resume_builder/tabs/edit_tabs/education_tabs/school.vue
resources/sass/resume_builder/components/inputs.scss

- Fixes eyes icons and backend function of edit elements.

Master to Production regular

---

resources/js/components/resume_builder/tabs/edit_tabs/Imports.vue

Master to Production - regualr

---

resources/js/components/auth/partials/RegisterForm.vue
resources/js/components/resume_builder/tabs/edit_tabs/Imports.vue

Imports manager tab

---

resources/js/components/welcome-view/welcome.vue

fixed login button for small screen

fixed login btn for sm screen

---

app/Http/Controllers/API/Admin/PromocodesController.php
app/Http/Controllers/API/UsersController.php
app/Subscription.php
database/migrations/2020_04_22_065422_create_subscriptions_table.php
resources/js/components/admin/tabs/General.vue

- Promo code | update functionality.

Feature: Promo code function.

---

resources/js/components/resume_builder/tabs/edit_tabs/PayAvailability.vue

- fixes Pay tab arrow page refresh issue .

Fix: payment tab arrow refresh page issue.

---

resources/js/components/resume_themes/theme1001/components/Header.vue
resources/js/components/resume_themes/theme1001/components/TabsNavigation.vue
resources/js/components/resume_themes/theme1001/scss/breakpoints.scss
resources/js/components/resume_themes/theme1001/views/Achievement.vue

fixed tab spacing, header background image...

fixed theme1001

---

app/Http/Controllers/API/ResumeLinksController.php
resources/js/components/resume_builder/tabs/edit_tabs/Imports.vue
resources/js/components/resume_builder/tabs/edit_tabs/imports_includes/ImportFromCIV.vue

- Record the import from civ resume.

Feature | record import of civ resume.

---

resources/js/components/resume_builder/tabs/EditCV.vue

- Add animation to the refresh button.

Update: refresh btn animation

---

app/Console/Kernel.php
app/Http/Controllers/Auth/LoginController.php

- updates login after restoring an account.

Updates cron job tasks and login after account restoring.

---

resources/js/components/resume_themes/theme5/index.vue

Fix bug: theme5 modal of hire me

---

resources/js/components/resume_builder/tabs/edit_tabs/AudioVideo.vue
resources/js/components/resume_builder/tabs/edit_tabs/Links.vue

- updates upload design for audio and video.

- Feature:

---

resources/js/themes/theme1001.js
resources/sass/themes/new/responsive/theme1001.scss
resources/sass/themes/new/theme1001.scss

- makes menu full-screen on phone.

- disables hover if menu is open.
